ALTER TABLE usage_logs
  MODIFY COLUMN account_billed DECIMAL(20,8) NOT NULL DEFAULT 0,
  MODIFY COLUMN user_billed DECIMAL(20,8) NOT NULL DEFAULT 0;

ALTER TABLE usage_stats_baseline
  MODIFY COLUMN account_billed DECIMAL(20,8) NOT NULL DEFAULT 0,
  MODIFY COLUMN user_billed DECIMAL(20,8) NOT NULL DEFAULT 0;

ALTER TABLE usage_stats_rollup
  MODIFY COLUMN account_billed DECIMAL(20,8) NOT NULL DEFAULT 0,
  MODIFY COLUMN user_billed DECIMAL(20,8) NOT NULL DEFAULT 0;

ALTER TABLE api_keys
  MODIFY COLUMN quota_limit DECIMAL(20,8) NOT NULL DEFAULT 0,
  MODIFY COLUMN quota_used DECIMAL(20,8) NOT NULL DEFAULT 0,
  MODIFY COLUMN total_used DECIMAL(20,8) NOT NULL DEFAULT 0;

ALTER TABLE user_api_keys
  MODIFY COLUMN quota_limit DECIMAL(20,8) NOT NULL DEFAULT 0,
  MODIFY COLUMN quota_used DECIMAL(20,8) NOT NULL DEFAULT 0;

ALTER TABLE api_key_scope_counters
  MODIFY COLUMN used_cost DECIMAL(20,8) NOT NULL DEFAULT 0;
