import { CheckCircle2, Loader2, Mail, Save, UserRound } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { Button } from '../../components/ui/button'
import { Input } from '../../components/ui/input'
import { Select } from '../../components/ui/select'
import { portalAPI, PortalAPIError } from '../../portal/api'
import type { PortalUser } from '../../portal/types'
import { useUserAuth } from '../../providers/AppProviders'

export default function ConsoleProfile() {
  const auth = useUserAuth()
  const [form, setForm] = useState<Pick<PortalUser, 'display_name' | 'phone' | 'locale' | 'timezone'>>({ display_name: auth.user?.display_name || '', phone: auth.user?.phone || '', locale: auth.user?.locale || 'zh-CN', timezone: auth.user?.timezone || 'Asia/Shanghai' })
  const [saving, setSaving] = useState(false)
  const [message, setMessage] = useState('')
  const [error, setError] = useState('')
  useEffect(() => { if (auth.user) setForm({ display_name: auth.user.display_name, phone: auth.user.phone, locale: auth.user.locale, timezone: auth.user.timezone }) }, [auth.user])
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); setMessage(''); try { await portalAPI.updateProfile(form); await auth.refresh(); setMessage('个人资料已保存') } catch (reason) { setError(reason instanceof PortalAPIError ? reason.message : '保存失败') } finally { setSaving(false) } }
  return <div className="mx-auto max-w-4xl space-y-6"><div><h2 className="text-2xl font-bold tracking-tight">个人资料</h2><p className="mt-1 text-sm text-muted-foreground">这些信息用于用户中心显示和本地化体验。</p></div><div className="grid gap-5 md:grid-cols-[220px_minmax(0,1fr)]"><aside className="rounded-2xl border border-border bg-card p-5 text-center shadow-sm"><div className="mx-auto flex size-20 items-center justify-center rounded-2xl bg-primary/10 text-2xl font-bold text-primary">{(auth.user?.display_name || auth.user?.email || 'U').slice(0, 1).toUpperCase()}</div><div className="mt-4 font-semibold">{auth.user?.display_name}</div><div className="mt-1 break-all text-xs text-muted-foreground">{auth.user?.email}</div><div className="mt-4 flex items-center justify-center gap-1.5 text-xs text-emerald-600"><CheckCircle2 className="size-3.5" />账号状态正常</div></aside><form onSubmit={submit} className="rounded-2xl border border-border bg-card p-6 shadow-sm"><div className="grid gap-5 sm:grid-cols-2"><Field label="昵称"><Input value={form.display_name} onChange={(event) => setForm({ ...form, display_name: event.target.value })} minLength={2} maxLength={64} required /></Field><Field label="注册邮箱"><div className="relative"><Mail className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={auth.user?.email || ''} disabled className="pl-10" /></div></Field><Field label="手机号码（可选）"><Input value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} placeholder="+86 13800000000" maxLength={32} /></Field><Field label="语言"><Select aria-label="语言" value={form.locale} onValueChange={(value) => setForm({ ...form, locale: value as PortalUser['locale'] })} options={[{ value: 'zh-CN', label: '简体中文' }, { value: 'zh-TW', label: '繁體中文' }, { value: 'en', label: 'English' }]} /></Field><Field label="时区" className="sm:col-span-2"><Select aria-label="时区" value={form.timezone} onValueChange={(value) => setForm({ ...form, timezone: value })} options={[{ value: 'Asia/Shanghai', label: 'Asia/Shanghai (UTC+8)' }, { value: 'Asia/Hong_Kong', label: 'Asia/Hong Kong (UTC+8)' }, { value: 'Asia/Tokyo', label: 'Asia/Tokyo (UTC+9)' }, { value: 'Europe/London', label: 'Europe/London' }, { value: 'America/Los_Angeles', label: 'America/Los Angeles' }, { value: 'UTC', label: 'UTC' }]} /></Field></div>{message && <div className="mt-5 rounded-lg border border-emerald-500/20 bg-emerald-500/8 px-3 py-2 text-sm text-emerald-600">{message}</div>}{error && <div className="mt-5 rounded-lg border border-red-500/20 bg-red-500/8 px-3 py-2 text-sm text-red-600">{error}</div>}<div className="mt-6 flex justify-end"><Button type="submit" disabled={saving}>{saving ? <Loader2 className="animate-spin" /> : <Save />}{saving ? '保存中…' : '保存资料'}</Button></div></form></div></div>
}

function Field({ label, children, className = '' }: { label: string; children: React.ReactNode; className?: string }) { return <div className={`block ${className}`}><div className="mb-1.5 text-sm font-medium">{label}</div>{children}</div> }
